feat(pubsub): Add publisher/subscriber system
starry-comet/comet-redis pull request #1
Opened 2017-03-12 21:53 UTC by FlorentinDUBOIS

Add publisher system
Add subscriber system
Add tests to each

2017-03-12 22:18 UTC, miton18 requested changes
smell very good

2017-03-12 22:18 UTC, miton18 commented on src/index.spec.ts
> +import 'reflect-metadata'
what are you importing ?

2017-03-12 22:18 UTC, miton18 commented on src/inversify.config.ts
> +import 'reflect-metadata'
what are you importing ?

2017-03-12 22:18 UTC, miton18 commented on src/redis/impl/RedisSubscriber.ts
> +        if (channel === chan) {
to be test but useless, if you subscribe on 1 chan youget messges for the same chan

2017-03-13 08:00 UTC, FlorentinDUBOIS commented on src/redis/impl/RedisSubscriber.ts
> +        if (channel === chan) {
in case of

2017-03-13 08:04 UTC, merged